version: '3.8'

volumes:
    laravel-mysql:
    laravel-redis:

networks:
    laravel-network:

services:
    nginx:
        build:
            context: .
            dockerfile: ./.docker/nginx/Dockerfile
        volumes:
            - ./:/var/www/html
            - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - '${APP_PORT:-80}:80'
        networks:
            - laravel-network
        depends_on:
            - php

    php:
        build:
            context: .
            dockerfile: ./.docker/php/Dockerfile
        volumes:
            - ./:/var/www/html
        networks:
            - laravel-network
        depends_on:
            - mysql

    mysql:
        build:
            context: .
            dockerfile: ./.docker/mysql/Dockerfile
        tty: true
        volumes:
            - laravel-mysql:/var/lib/mysql
        ports:
            - '${DB_PORT:-3306}:3306'
        environment:
            MYSQL_DATABASE: '${DB_DATABASE}'
            # MYSQL_USER: '${DB_USERNAME}'
            # MYSQL_PASSWORD: '${DB_PASSWORD}'
            # MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            # MYSQL_ALLOW_EMPTY_PASSWORD: 1
        networks:
            - laravel-network

    node:
        build: ./.docker/node
        tty: true
        volumes:
            - ./:/var/www/html

    # redis:
    #     image: redis:alpine
    #     volumes:
    #         - "laravel-redis:/data"
    #     ports:
    #         - '${REDIS_PORT:-6379}:6379'
    #     networks:
    #         - laravel-network

    smtp:
        image: rnwood/smtp4dev:linux-amd64-v3
        ports:
            - 1000:80
        networks:
            - laravel-network
